fix typescript-to-lua/language-extensions error
typescript-to-lua/language-extensions is a separate npm package named "@typescript-to-lua/language-extensions" since 2022-09-04 https://github.com/TypeScriptToLua/TypeScriptToLua/pull/1345

using it without "@" at the front leads to a compilation error "error TS2688: Cannot find type definition file for 'typescript-to-lua/language-extensions'"